title: '<audio>: The Embed Audio element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/audio
tags:
    group: Image and multimedia
api: HTMLAudioElement
permitted-aria-roles: application
tag_omission: none
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/audio.html
browser-compatibility: html.elements.audio
examples:
    - examples/simple-example
    - examples/audio-element-with-video-element
    - examples/multiple-source-elements
attributes:
    element-specific: ./attributes
    global: /content/html/global_attributes
recipe: html-element
