title: '<br>: The Line Break element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/br
tags:
    group: Inline text semantics
api: HTMLBRElement
permitted-aria-roles: any
tag_omission: no-closing-tag
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/br.html
browser-compatibility: html.elements.br
examples:
    - examples/simple-example
attributes:
    element-specific: ./attributes
    global: /content/html/global_attributes
recipe: html-element
