title: '<footer>'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/footer
tags:
    group: Content sectioning
api: HTMLElement
permitted-aria-roles:
    - group
    - presentation
tag_omission: none
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/footer.html
browser-compatibility: html.elements.footer
examples:
    - examples/simple-example
attributes:
    global: /content/html/global_attributes
recipe: html-element
