title: '<col>'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/col
tags:
    group: Table content
api: HTMLTableColElement
permitted-aria-roles: none
tag_omission: no-closing-tag
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/col.html
browser-compatibility: html.elements.col
examples:
    - examples/simple-example
attributes:
    element-specific: ./attributes
    global: /content/html/global_attributes
recipe: html-element
