title: '<code>: The Inline Code element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/code
tags:
    group: Inline text semantics
api: HTMLElement
permitted-aria-roles: any
tag_omission: none
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/code.html
browser-compatibility: html.elements.code
examples:
    - examples/simple-example
attributes:
    global: /content/html/global_attributes
recipe: html-element
