title: '<label>'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/label
tags:
    group: Forms
api: HTMLLabelElement
permitted-aria-roles: none
tag_omission: none
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/label.html
browser-compatibility: html.elements.label
examples:
    - examples/simple-example
    - examples/using-for-attribute
attributes:
    element-specific: ./attributes
    global: /content/html/global_attributes
recipe: html-element
