title: '<embed>: The Embed External Content element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/embed
tags:
    group: Embedded content
api: HTMLEmbedElement
permitted-aria-roles:
    - application
    - document
    - img
    - presentation
tag_omission: no-closing-tag
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/embed.html
browser-compatibility: html.elements.embed
examples:
    - examples/simple-example
attributes:
    element-specific: ./attributes
    global: /content/html/global_attributes
recipe: html-element
