title: '<figure>'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/figure
tags:
    group: Text content
api: HTMLElement
permitted-aria-roles:
    - group
    - presentation
tag_omission: none
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/figure.html
browser-compatibility: html.elements.figure
examples:
    - examples/images
    - examples/code-snippets
    - examples/quotations
    - examples/poems
attributes:
    global: /content/html/global_attributes
recipe: html-element
