title: '<header>'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/header
tags:
    group: Content sectioning
api: HTMLElement
permitted-aria-roles:
    - group
    - presentation
tag_omission: none
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/header.html
browser-compatibility: html.elements.header
examples:
    - examples/page-header
    - examples/article-header
attributes:
    global: /content/html/global_attributes
recipe: html-element
