title: '<canvas>: The Graphics Canvas element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/canvas
tags:
    group: Scripting
api: HTMLCanvasElement
permitted-aria-roles: any
tag_omission: none
browser-compatibility: html.elements.canvas
examples:
    - examples/simple-example
    - examples/opaque-canvas
attributes:
    element-specific: ./attributes
    global: /content/html/global_attributes
recipe: html-element
