language: node_js
node_js: stable
cache: npm
branches:
  only:
    - master

script:
  - npm run ci-checks
  - npm test
  # Note, in a near future we're going to want to build-json for *everything*
  # and not just the 'html' section.
  - npm run build-json html
  - npm run mdn-sitemap-compare
