title: '<blockquote>: The Block Quotation element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/blockquote
tags:
    group: Text content
api: HTMLQuoteElement
permitted-aria-roles: any
tag_omission: none
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/blockquote.html
browser-compatibility: html.elements.blockquote
examples:
    - examples/simple-example
attributes:
    global: /content/html/global_attributes
recipe: html-element
