title: '<ins>'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/ins
tags:
    group: Inline text semantics
api: HTMLModElement
permitted-aria-roles: any
tag_omission: none
browser-compatibility: html.elements.ins
examples:
    - examples/simple-example
attributes:
    element-specific: ./attributes
    global: /content/html/global_attributes
recipe: html-element
