title: '<aside>: The Aside element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/aside
tags:
    group: Flow content
api: HTMLElement
permitted-aria-roles:
    - feed
    - note
    - presentation
    - region
    - search
tag_omission: none
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/aside.html
browser-compatibility: html.elements.aside
examples:
    - examples/simple-aside-example
attributes:
    global: /content/html/global_attributes
recipe: html-element
