title: '<button>: The Button element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/button
tags:
    group: Forms
api: HTMLButtonElement
permitted-aria-roles:
    - checkbox
    - link
    - menuitem
    - menuitemcheckbox
    - menuitemradio
    - radio
    - switch
    - tab
tag_omission: none
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/button.html
browser-compatibility: html.elements.button
examples:
    - examples/simple-example
attributes:
    element-specific: ./attributes
    global: /content/html/global_attributes
recipe: html-element
