title: '<fieldset>: The Field Set element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/fieldset
tags:
    group: Forms
api: HTMLFieldSetElement
permitted-aria-roles:
    - group
    - presentation
tag_omission: none
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/fieldset.html
browser-compatibility: html.elements.fieldset
examples:
    - examples/simple-example
    - examples/disabled-fieldset
attributes:
    element-specific: ./attributes
    global: /content/html/global_attributes
recipe: html-element
