title: '<iframe>: The Inline Frame element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/iframe
tags:
    group: Embedded content
api: HTMLIFrameElement
permitted-aria-roles:
    - application
    - document
    - img
tag_omission: none
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/iframe.html
browser-compatibility: html.elements.iframe
examples:
    - examples/simple-maps-example
attributes:
    element-specific: ./attributes
    global: /content/html/global_attributes
recipe: html-element
