title: '<figcaption>'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/figcaption
tags:
    group: Text content
api: HTMLElement
permitted-aria-roles:
    - group
    - presentation
tag_omission: none
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/figcaption.html
browser-compatibility: html.elements.figcaption
examples:
    - examples/simple-example
attributes:
    global: /content/html/global_attributes
recipe: html-element
