title: '<article>: The Article Contents element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/article
tags:
    group: Flow content
api: HTMLElement
permitted-aria-roles:
    - application
    - document
    - feed
    - main
    - presentation
    - region
tag_omission: none
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/article.html
browser-compatibility: html.elements.article
examples:
    - examples/simple-article-example
attributes:
    global: /content/html/global_attributes
recipe: html-element
