title: '<i>'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/i
tags:
    group: Inline text semantics
api: HTMLElement
permitted-aria-roles: any
tag_omission: none
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/i.html
browser-compatibility: html.elements.i
examples:
    - examples/simple-example
attributes:
    global: /content/html/global_attributes
recipe: html-element
