title: '<h1>–<h6>: The HTML Section Heading elements'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/Heading_Elements
tags:
    group: Content sectioning
api: HTMLHeadingElement
permitted-aria-roles:
    - tab
    - presentation
tag_omission: none
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/h1-h6.html
browser-compatibility: html.elements.h1
examples:
    - examples/all-headings
    - examples/example-page
attributes:
    global: /content/html/global_attributes
recipe: html-element
