title: '<form>'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/form
tags:
    group: Forms
api: HTMLFormElement
permitted-aria-roles:
    - group
    - presentation
tag_omission: none
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/form.html
browser-compatibility: html.elements.form
examples:
    - examples/simple-example
attributes:
    element-specific: ./attributes
    global: /content/html/global_attributes
recipe: html-element
