title: '<base>: The Document Base URL element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/base
tags:
    group: Document metadata
api: HTMLBaseElement
permitted-aria-roles: none
tag_omission: no-closing-tag
browser-compatibility: html.elements.base
examples:
    - examples/simple-example
attributes:
    element-specific: ./attributes
    global: /content/html/global_attributes
recipe: html-element
