title: '<dialog>: The Dialog element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/dialog
tags:
    group: Interactive elements
api: HTMLDialogElement
permitted-aria-roles: alertdialog
tag_omission: none
browser-compatibility: html.elements.dialog
examples:
    - examples/simple-example
    - examples/advanced-example
attributes:
    element-specific: ./attributes
    global: /content/html/global_attributes
recipe: html-element
