title: '<del>: The Deleted Text element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/del
tags:
    group: Demarcating edits
api: HTMLModElement
permitted-aria-roles: any
tag_omission: none
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/del.html
browser-compatibility: html.elements.del
examples:
    - examples/simple-example
attributes:
    element-specific: ./attributes
    global: /content/html/global_attributes
recipe: html-element
