title: '<video>: The Video Embed element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/video
tags:
    group: Image and multimedia
api: HTMLVideoElement
permitted-aria-roles: application
tag_omission: none
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/video.html
browser-compatibility: html.elements.video
examples:
    - examples/simple-example
    - examples/multiple-sources-example
attributes:
    element-specific: ./attributes
    global: /content/html/global_attributes
recipe: html-element
