title: '<html>: The HTML Document / Root element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/html
tags:
    group: Main root
api: HTMLHtmlElement
permitted-aria-roles: none
tag_omission:
browser-compatibility: html.elements.html
examples:
    - examples/simple-example
attributes:
    element-specific: ./attributes
    global: /content/html/global_attributes
recipe: html-element
