title: '<hr>: The Thematic Break (Horizontal Rule) element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/hr
tags:
    group: Text content
api: HTMLElement
permitted-aria-roles:
    - presentation
tag_omission: no-closing-tag
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/hr.html
browser-compatibility: html.elements.hr
examples:
    - examples/simple-example
attributes:
    global: /content/html/global_attributes
recipe: html-element
