title: '<cite>: The Citation element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/cite
tags:
    group: Text content
api: HTMLElement
permitted-aria-roles: any
tag_omission: none
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/cite.html
browser-compatibility: html.elements.cite
examples:
    - examples/simple-example
attributes:
    global: /content/html/global_attributes
recipe: html-element
