title: '<bdi>: The Bidirectional Isolate element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/bdi
tags:
    group: Inline text semantics
api: HTMLElement
permitted-aria-roles: any
tag_omission: none
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/bdi.html
browser-compatibility: html.elements.bdi
examples:
    - examples/ltr-only-example
    - examples/ltr-rtl-example
    - examples/ltr-rtl-bdi-example
attributes:
    global: /content/html/global_attributes
recipe: html-element
