title: '<details>: The Details disclosure element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/details
tags:
    group: Interactive elements
api: HTMLDetailsElement
permitted-aria-roles: none
tag_omission: none
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/details.html
browser-compatibility: html.elements.details
examples:
    - examples/simple-example
    - examples/providing-a-summary
    - examples/open-disclosure-box
    - examples/customising-the-appearance
    - examples/customising-the-disclosure-widget
attributes:
    element-specific: ./attributes
    global: /content/html/global_attributes
recipe: html-element
