title: '<bdo>: The Bidirectional Text Override element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/bdo
tags:
    group: Inline text semantics
api: HTMLElement
permitted-aria-roles: any
tag_omission: none
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/bdo.html
browser-compatibility: html.elements.bdo
examples:
    - examples/simple-example
attributes:
    global: /content/html/global_attributes
recipe: html-element
