title: '<table>: The Table element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/table
tags:
    group: Flow content
api: HTMLTableElement
permitted-aria-roles:
    - *
tag_omission: none
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/table.html
browser-compatibility: html.elements.table
examples:
    - examples/simple-example
    - examples/complex-example
attributes:
    element-specific: ./attributes
    global: /content/html/global_attributes
recipe: html-element
