title: '<em>: The Emphasis element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/em
tags:
    group: Inline text semantics
api: HTMLElement
permitted-aria-roles: any
tag_omission: none
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/em.html
browser-compatibility: html.elements.em
examples:
    - examples/simple-example
attributes:
    global: /content/html/global_attributes
recipe: html-element
