title: '<legend>'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/legend
tags:
    group: Forms
api: HTMLLegendElement
permitted-aria-roles: none
tag_omission: none
interactive-example: https://interactive-examples.mdn.mozilla.net/pages/tabbed/legend.html
browser-compatibility: html.elements.legend
examples:
    - examples/simple-example
attributes:
    global: /content/html/global_attributes
recipe: html-element
