title: '<body>: The Document Body element'
mdn-url: https://developer.mozilla.org/docs/Web/HTML/Element/body
tags:
    group: Sectioning root
api: HTMLBodyElement
permitted-aria-roles: none
tag_omission:
browser-compatibility: html.elements.body
examples:
    - examples/simple-example
attributes:
    global: /content/html/global_attributes
recipe: html-element
